# Generated by Django 5.2.3 on 2025-06-22 10:12

import image_processor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(help_text='Original image uploaded by user', upload_to=image_processor.models.upload_to_original)),
                ('processed_image', models.ImageField(blank=True, help_text='AI-processed cartoon image', null=True, upload_to=image_processor.models.upload_to_processed)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Time taken to process in seconds', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
            ],
            options={
                'verbose_name': 'Image Processing',
                'verbose_name_plural': 'Image Processings',
                'ordering': ['-created_at'],
            },
        ),
    ]
